[package]
name = "stroke"
version = "0.1.0"
authors = ["Dorian Prill"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyvec = "^0.3.3"


[dependencies.num-traits]
version = "^0.2"
default-features = false
features = ["libm"]    # <--- Uncomment if you wish to use `Float` and `Real` without `std`


# these are just for development (e.g. integration tests and examples)
[dev-dependencies]
plotters = "^0.2.12"